<?php

namespace App\Entity;

use PHPUnit\Framework\TestCase;

/**
 * Test cases for class Book.
 */
class BookTest extends TestCase
{
    public function testGetAttributesAsArray()
    {
        $book = new Book();
        $book->setTitle('Test Book');
        $book->setIsbn('1234567890');
        $book->setAuthor('Test Author');
        $book->setImg('test.jpg');
        $book->setPublishedYear(2022);
        $book->setDescription('Test description');

        $expectedArray = [
            'id' => null, // Since the ID is generated by the database, it will be null for a new book.
            'title' => 'Test Book',
            'isbn' => '1234567890',
            'author' => 'Test Author',
            'img' => 'test.jpg',
            'publishedYear' => 2022,
            'description' => 'Test description',
        ];

        $this->assertEquals($expectedArray, $book->getAttributesAsArray());
    }
}